sonar.projectKey=hub-backends
sonar.projectName=Hub Empresarial - Backends
sonar.sourceEncoding=UTF-8

sonar.modules=modulo_acreditacion,modulo_administracion,modulo_bodega,modulo_mantencion,modulo_middleware,modulo_prevencion,modulo_rrhh,modulo_watchdog

modulo_acreditacion.sonar.projectName=modulo_acreditacion
modulo_acreditacion.sonar.sources=src
modulo_acreditacion.sonar.tests=src/tests
modulo_acreditacion.sonar.python.coverage.reportPaths=modulo_acreditacion/coverage.xml
modulo_acreditacion.sonar.exclusions=src/tests/**

modulo_administracion.sonar.projectName=modulo_administracion
modulo_administracion.sonar.sources=src
modulo_administracion.sonar.tests=src/tests
modulo_administracion.sonar.python.coverage.reportPaths=modulo_administracion/coverage.xml
modulo_administracion.sonar.exclusions=src/tests/**

modulo_bodega.sonar.projectName=modulo_bodega
modulo_bodega.sonar.sources=src
modulo_bodega.sonar.tests=src/tests
modulo_bodega.sonar.python.coverage.reportPaths=modulo_bodega/coverage.xml
modulo_bodega.sonar.exclusions=src/tests/**

modulo_mantencion.sonar.projectName=modulo_mantencion
modulo_mantencion.sonar.sources=src
modulo_mantencion.sonar.tests=src/tests
modulo_mantencion.sonar.python.coverage.reportPaths=modulo_mantencion/coverage.xml
modulo_mantencion.sonar.exclusions=src/tests/**

modulo_middleware.sonar.projectName=modulo_middleware
modulo_middleware.sonar.sources=.
modulo_middleware.sonar.tests=src/tests
modulo_middleware.sonar.python.coverage.reportPaths=modulo_middleware/coverage.xml
modulo_middleware.sonar.exclusions=src/tests/**,.venv_test/**

modulo_prevencion.sonar.projectName=modulo_prevencion
modulo_prevencion.sonar.sources=src
modulo_prevencion.sonar.tests=src/tests
modulo_prevencion.sonar.python.coverage.reportPaths=modulo_prevencion/coverage.xml
modulo_prevencion.sonar.exclusions=src/tests/**

modulo_rrhh.sonar.projectName=modulo_rrhh
modulo_rrhh.sonar.sources=src
modulo_rrhh.sonar.tests=src/tests
modulo_rrhh.sonar.python.coverage.reportPaths=modulo_rrhh/coverage.xml
modulo_rrhh.sonar.exclusions=src/tests/**

modulo_watchdog.sonar.projectName=modulo_watchdog
modulo_watchdog.sonar.sources=.
modulo_watchdog.sonar.tests=src/tests
modulo_watchdog.sonar.python.coverage.reportPaths=modulo_watchdog/coverage.xml
modulo_watchdog.sonar.exclusions=src/tests/**,.venv_test/**
